# Application Configuration
spring.application.name=Movie Management System
server.port=8082

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/movie_management_db
spring.datasource.username=postgres
spring.datasource.password=kigali123

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging Configuration
logging.level.movie.rw=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
